args <- commandArgs(trailingOnly=TRUE)
library(ape)
distm<-read.table(args[1], header = TRUE, row.names = 1)
mdist.dist <- as.dist(distm)
nj.tree <- nj(mdist.dist)
max.dist <- max(node.depth.edgelength(nj.tree))
root.node <- which(node.depth.edgelength(nj.tree) == max.dist)
rooted.tree <- root(nj.tree, root.node)
write.tree(rooted.tree,file=args[2])